### ISSUE TITLE
site-title tagging

### ISSUE THREAD

**Issue by topher1kenobe** [easydigitaldownloads/vendd#174]
The site-title isn't wrapped in an H1.  I assume there's a reason, I'd love to hear it.

Additionally however, when a logo is used, the site title isn't printed at all, leaving Google no idea what the site is,

**Comment by SDavisMedia** [comment]
You'd love to hear it?

Google knows what the site is because of the `title` tag. Always. But not having the site name used anywhere when a logo is in use is an oversight. It just needs to be a title attribute on the `img` element. Not hurting anything not having it but I should add it. 

Wrapping a site title in `h1` is not necessary. If you ask me, it's wrong. Each page of a website is its own document serving a specific purpose. You can build a header in a templating system and treat it like no other part of the page will ever exist below it or you can take into account that the content will explain the document's purpose, not the overall page header. Vendd takes the second approach and uses `h1` elements in the content itself explaining what the overall document is about or what the individual semantic HTML5 sections are about.

Search engines do not use a webpage's `h1` tag to get a site title. It uses the `title` tag. The structure of the document in regard to headings is built once you get to the unique part of the page. You'll find it difficult to find a page in Vendd that does not have an `h1` that explains the actual purpose of the document (post, page, download, archives... they all use an `h1` for the relevant document title... not the site title). It's been this way for years not only with changes to how search engines read pages, but also in the differences between traditional HTML and HTML5.

There's no bug here. Again, though, I'll add a title attribute with a site name to the logo.
