### ISSUE TITLE
On [downloads] bind js events to body

### ISSUE THREAD

**Issue by rubengc** [easydigitaldownloads/vendd#200]
to support ajax loaded content

**Comment by SDavisMedia** [comment]
@rubengc explain what you're referring to in more detail please, and why this should be in Vendd as opposed to custom for your application of the theme. Thanks!

**Comment by rubengc** [comment]
Oh yes, on [downloads] you have a js functionallity to show/hide purchase button

This listener is binded directly to the button instead to the body, so If you load the page from ajax, you can not show the purchase button

Sorry I forgive complete the issue :/

**Comment by davidsherlock** [comment]
@SDavisMedia, this is actually a pretty big one as I had the same issue while developing a child theme for the Array Themes Checkout theme. When you use something like FacetWP, the AJAX handling breaks some of the theme functionality due to the way Javascript click events are handled within the theme. I had to effectively re-write the checkout javascript to make it work.

E.g. before:

`$(".download-price-toggle a").click(function(e) {`

After:

`$(document).on('click', '.download-price-toggle a', function(e) {`

This should be a pretty easy fix as @rubengc mentioned, and worth including for people who want to use AJAX filtering plugins.

**Comment by SDavisMedia** [comment]
Lost track of this issue. Sorry, @rubengc. I'll get it in the next release for sure.

**Comment by rubengc** [comment]
Do not worry, unique plugins i know that are using ajax in [downloads] are my own, so feel free to fix It when you want/can

**Comment by SDavisMedia** [comment]
@rubengc can you test branch `issue/200` for me with your use case?

**Comment by davidsherlock** [comment]
Sean, can you run a quick test with FacetWP to make sure the changes work? Plan on adding FacetWP searching and filtering to theme.

**Comment by SDavisMedia** [comment]
@davidsherlock I don't have FacetWP set up in my Vendd environment. You can let me know if you run into issues, though.

**Comment by rubengc** [comment]
It works to me now, thanks @SDavisMedia ^^

**Comment by SDavisMedia** [comment]
@davidsherlock I ended up setting up FacetWP. It actually worked fine without binding the event to the body. Still works after the change, though.

**Comment by davidsherlock** [comment]
@SDavisMedia, did you try any mobile testing? I noticed with the Checkout theme that's where the issues started appearing due to the restrictions on javascript events on mobile devices (specifically iOS).

**Comment by SDavisMedia** [comment]
@davidsherlock I did not.

**Comment by SDavisMedia** [comment]
Scratch that... not working fully with FacetWP yet. Working on it.
