### ISSUE TITLE
Advanced search results missing categories/tags and extracted excerpt

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/vendd#210]
The advanced search results don't contain the categories or tags, nor do they contain if the excerpt field is left blank. Ideally the excerpt should be extracted from the post body content with a character limit imposed.

**Comment by SDavisMedia** [comment]
@davidsherlock the excerpt is definitely missing from the downloads for some reason. 🤔 That must have broken at some point.

I don't follow what you're saying about categories and tags, though. They show on the downloads just fine.

**Comment by davidsherlock** [comment]
Apologies @SDavisMedia, the categories and tags are working. The excerpts are the main issue, any ideas how to fix quickly at my side?

**Comment by SDavisMedia** [comment]
@davidsherlock good catch here. This is happening because I'm trying to use some EDD templates that are expected to be used in the loop. https://github.com/easydigitaldownloads/vendd/blob/master/content/content-advanced-search.php#L27

I'll have to change my approach since this is coming from a custom query. Working on it now.

**Comment by SDavisMedia** [comment]
That should do it.

**Comment by davidsherlock** [comment]
Working good here @SDavisMedia! Thanks.
