### ISSUE TITLE
Download page FES store name improvement

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/vendd#218]
On the download archive page product boxes it would be better show the store name (as set in FES) rather than author/display name. The same goes for the download page sidebar (though simply having an additional "Store name" field be would suffice here).

Technically speaking an author _owns_ and operates a store that they trade under, so I see the thinking behind showing author details rather than store name until clicked, but from a usability standpoint prioritising the FES store name probably makes the most sense on the frontend since people will associate with the author or company brand before a username.

**Comment by SDavisMedia** [comment]
@davidsherlock I like that approach. 

This is a gray area of FES that we've been discussing recently because of a separate issue. There's an idea that FES is used for giving vendor's stores when in reality, they have no stores. There's only one store, and vendors (who are not truly vendors at all) simply have the ability to submit products to the store. Same idea as one of use submitting a plugin to the WordPress plugin directory. 

The confusion comes from how FES has been branded and used in the past with other integrated extensions. In my eyes, and based on the actual functionality of FES, submitting a product is like contributing posts to a blog you don't own. And when the post/product is displayed, you display contributor information.

However, we plan to fix this in the future. Everyone's expectations of what FES is and how it should work are already set. And I believe we're going to make some major enhancements to bring real functionality to match those expectations. What you're suggesting here is definitely in line with those expectations. So I see no harm in allowing Vendd to fake the funk a little early in the game. :+1:

**Comment by SDavisMedia** [comment]
@davidsherlock give `issue/218` branch a try. On the downloads grid, the store name shows only if it exists. If it doesn't, it falls back to the vendor name. On the single download pages, the store name displays below the vendor avatar (if it exists) and can be removed via filter like other sidebar elements.

**Comment by davidsherlock** [comment]
@SDavisMedia, this is actually an area I researched pretty in depth but could not find anything that gave a clear definition of a vendor, author/contributor and commissions in relation to digital product reselling rather than affiliation.

I am based in the UK but I keep seeing the term "commission" used in relation to other businesses reselling/retailing digital products. It seems like some kind of agency, distributor and/or reseller model. In fact most third party eCommerce software solutions also refer to paying _vendors_ a "commission" on each sale of their digital products. This confuses me as the "author" is effectively uploading a product for sale (and granting a royalty-free and/or fully paid license/rights to us to distribute/resell on a royalty-free basis usually) and in return they receive an 80% "commission" payment per product sold (with us effectively taking a 20% cut for our platform services). The advantage of this model is the "store" (or marketplace) can be responsible for invoicing the customer and handling handling sales taxes (since as you say they aren't technically a _vendor_ as you mention). This keeps invoicing simpler because the marketplace "commission" paid out isn't seen as a separate supply of service by revenue services and thus only two invoices are needed (one from the site to the customer and one monthly from the vendor/author to the marketplace for their commission).

This seems to go against the traditional meaning of "commission" where a sales representative or affiliate is paid a "commission" for a service they render (referring a client, lead generation, etc.). Similarly it feels like our services are actually a "commission" on each sale rather than the inverse since we are promoting the product. 

I actually spoke to @pippinsplugins in relation to this question and he gave the following response:

> We don't own the plugins so we're not paying royalties. We simply provide the sales system and take a small percentage of each sale in exchange.
> 
> It's similar to how car dealerships and real estate companies give their agents sale commissions.

Maybe someone can provide some clarity on this since it falls inline with the feature suggested above and I'm sure creates confusion for other customers using FES/Commissions.

**Comment by davidsherlock** [comment]
@SDavisMedia, that commit works great btw! Looks good as well on the sidebar.

I have only one minor suggestion, everytime I see an avatar I feel it should be clickable to the profile page (with the exception of the smaller ones on the archive pages). Thoughts? :)

**Comment by SDavisMedia** [comment]
@davidsherlock Give that a try.

**Comment by davidsherlock** [comment]
Thanks Sean, I'll give this a try when home!

**Comment by davidsherlock** [comment]
@SDavisMedia, for some reason this isn't working for me, the avatar has no url assigned to it. Any ideas? I am half asleep so probably better checking in the morning :)

**Comment by SDavisMedia** [comment]
@davidsherlock make sure you're on `issue/218` ... this isn't in `master` just yet.
