### ISSUE TITLE
Download details fes integration

### ISSUE THREAD

**Issue by davidsherlock** [easydigitaldownloads/vendd#227]
FES outputs a table with the various details set during the submissions process, however this table is inserted below the content meaning the details can be easily missed. 

I could not find any filters or ways of 'redirecting' the table to somewhere more suitable like the sidebar, but I may be missing something here? Thought it would be a worthwhile suggestion for Vendd core.

**Comment by davidsherlock** [comment]
I actually implemented this feature into my theme called "Product Features", where key bullet points can be set on a per-product basis to show on the sidebar.

![screenshot 2017-05-28 22 47 33](https://cloud.githubusercontent.com/assets/22668877/26532400/da8b0ae8-43f7-11e7-800c-1fb8a75a7cd6.png)

**Comment by SDavisMedia** [comment]
Nice idea but not the best fit for something like Vendd. While we do want people to like the theme, the goal isn't for it to be a commercial theme that everyone flocks to for its features. Instead, it needs to showcase default features of the extensions it supports.

Vendd can occasionally spice things up a bit by displaying available data like software licensing information (because it doesn't display by default). But it doesn't need to go into full-on custom development like moving default actions around, using its own products display template while ignoring the downloads shortcode (most EDD themes do that, even some I've built), etc. Get too deep into that and all of a sudden this free, on-boarding theme turns into a source of confusion as new users get familiar with their purchased extensions. Extension docs end up in direct contradiction with what they see in the free theme we told them to use.

I definitely encourage you to go all out on your Vendd fork and do a lot of custom development. But keep in mind that who will use a theme, when they will use it, and how they will use it is usually just as important as its functionality and design. If you're building yours for profit (you definitely should be), you'll be making different decisions than us.

**Comment by davidsherlock** [comment]
With you 100% @SDavisMedia, completely agree.

I am actually building this theme for myself primarily with the hope of also making it commercial, since it should cover most of what people want/need for a larger scale marketplace solution.

While I am aware this isn't your area, do you have any tips/clues into how to achieve the above?

**Comment by davidsherlock** [comment]
@SDavisMedia, as a side I will cool it with the suggestions for the time being - appreciate your help this far btw!

**Comment by SDavisMedia** [comment]
@davidsherlock tips on how to achieve meeting the needs of those looking to build a larger scale marketplace? If that's what you're asking, I don't have very many off the top of my head, unfortunately. I usually keep my thinking inline with what I like to see as an actual shopper. So I get a lot of tips from sites like Amazon. And of course the more functionality/features you can take advantage of in our [Marketplace Bundle](https://easydigitaldownloads.com/downloads/marketplace-bundle/), the better. I think it's worth it to go all out on Wish Lists, Recommended Products, Points & Rewards, and Reviews. Positioning their output in a way that is similar to sites like Amazon would go a long way in the EDD theme space.

**Comment by davidsherlock** [comment]
Good advice Sean, however I should have been clearer. I was actually referring to moving the position of the FES table to the sidebar (if possible)? Can't see any 'easy' way to achieve this out of the box, other than rebuilding the output.

**Comment by SDavisMedia** [comment]
@davidsherlock oh I'm not sure. Have a look at Marketify and its product fields plugin: https://wordpress.org/plugins/easy-digital-downloads-frontend-submissions-product-details-widget/ It was probably created for the same reason.
