### ISSUE TITLE
footer

### ISSUE THREAD

**Issue by emyabdel** [easydigitaldownloads/vendd#264]
Hi, when I go to appearance/widgets I can't find the footer area. I find just main sidebar and downloads sidebar. How to add footer there? Thanks

**Comment by cklosowski** [comment]
@emyabdel Vendd does not have a widigetized footer area, if I'm not mistaken. @SDavisMedia can you confirm?

**Comment by emyabdel** [comment]
Yes Vendd doesn't have a footer widget area, but I need to add it because footer is important

**Comment by SDavisMedia** [comment]
Hi @emyabdel. It's possible that some time in the future, Vendd will have a widgetized footer area. But it's not currently planned. So if it's something you need sooner than later, it's best to create it yourself or hire someone to do the development for you. For someone with WordPress theme development experience, it would be a fairly straightforward job.

**Comment by emyabdel** [comment]
Yes i want it sooner and I want that someone tell me how to do it and do it myself because i have ftp access

**Comment by SDavisMedia** [comment]
@emyabdel That's not something we can help you with because it's custom development. You'll need to follow articles on how to add widgetized areas (known as sidebars) to themes, or hire someone to do it for you. Perhaps you can contact a [consultant ](https://easydigitaldownloads.com/consultants/) for help.

**Comment by emyabdel** [comment]
Ok thanks a lot
