### ISSUE TITLE
Combine (maybe minify) JavaScript

### ISSUE THREAD

**Issue by SDavisMedia** [easydigitaldownloads/vendd#67]
There are [6 JS files](https://github.com/easydigitaldownloads/vendd/tree/master/inc/js) at the moment. That could be a little more efficient, I think.

**Comment by tnorthcutt** [comment]
Seems reasonable to combine `navigation.js`, `vendd-scripts.js`, and `skip-link-focus-fix.js`, since they're all enqueued unconditionally. You could probably also make a case for including `parallax.js` in that – it would make the resulting file bigger than necessary for some people, but only a tiny bit, and would mean one less http request for others.
